### ISSUE TITLE
Lane Detector - initial

### ISSUE THREAD

**Issue by lbrombach** [waynerobotics/veronica#12]
Add existing lane detection package to veronica project.

**Comment by ringo47** [comment]
No changes to code for this one. Moved into the mapping folder along with other lane_* packages.
Tested on the robot and on bag files for white gauges. The main script is [lane_tracker.py](https://github.com/waynerobotics/veronica/blob/main/src/igvc_navigation/mapping/lane_follower/Scripts/lane_tracker.py)
