### ISSUE TITLE
Lane to laser implementation

### ISSUE THREAD

**Issue by lbrombach** [waynerobotics/veronica#14]
Add existing lane to laser to veronica project

**Comment by ringo47** [comment]
Calibrated close enough with the laser->map transform in [lane_to_laser_hokyo_bag.launch](https://github.com/waynerobotics/veronica/blob/main/src/igvc_navigation/mapping/lane_laser_scan/launch/lane_to_laser_hokyo_bag.launch). @lbrombach , build and test it with the _**2020_11_06_camera_lidar.bag**_ bag file.
(eg: `roslaunch lane_laser_scan lane_to_laser_hokyo_bag.launch filename_true:=/home/ringo/waynerobotics/veronica/bags/2020_11_06_camera_lidar.bag`)

**Comment by ringo47** [comment]
Will add documentation for the math in wiki later.

**Comment by ringo47** [comment]
Confirmed test run with @lbrombach . Closing.
