### ISSUE TITLE
scan merger

### ISSUE THREAD

**Issue by lbrombach** [waynerobotics/veronica#16]
Add ira laser tools scan merger to veronica project.

**Comment by ringo47** [comment]
[ira_laser_tools](https://github.com/waynerobotics/veronica/tree/main/src/igvc_navigation/mapping/ira_laser_tools) also moved into mapping folder. The merge script is invoked with the [lane_to_laser_hokuyo.launch](https://github.com/waynerobotics/veronica/blob/main/src/igvc_navigation/mapping/lane_laser_scan/launch/lane_to_laser_hokuyo.launch).
